2 packages from uemurax/satysfi-arrows at 0.1.0
na4zagin3/satyrographos-repo pull request #175
Opened 2020-09-08 20:24 UTC by uemurax

A SATySFi arrows library

This pull-request concerns:
-`satysfi-arrows.0.1.0`
-`satysfi-arrows-doc.0.1.0`

---
* Homepage: https://github.com/uemurax/satysfi-arrows
* Source repo: git+https://github.com/uemurax/satysfi-arrows.git
* Bug tracker: https://github.com/uemurax/satysfi-arrows/issues

---
:camel: Pull-request generated by opam-publish v2.0.2

2020-09-09 09:31 UTC, na4zagin3 requested changes
Could you please fix the CI?

2020-09-09 09:31 UTC, na4zagin3 commented on snapshot-stable-0-0-5.opam
> +  "satysfi-arrows" {= "0.1.0"}
SATySFi 0.0.5 cannot not compile example.saty.  Can you remove these two lines?

```suggestion
```

Build logs:

```
- Reading runtime dist: /home/travis/.opam/ocaml-base-compiler.4.10.1/share/satysfi/dist
- Read user libraries: ()
- Reading opam libraries: (arrows assert-eq base bibyfi bibyfi-doc cancel class-exdesign
-  class-exdesign-doc class-slydifi class-stjarticle class-stjarticle-doc
-  debug-show-value dist easytable fonts-asana-math fonts-asana-math-doc
-  fonts-computer-modern-unicode fonts-dejavu fonts-dejavu-doc fonts-noto-emoji
-  fonts-noto-sans fonts-noto-sans-cjk-jp fonts-noto-serif
-  fonts-noto-serif-cjk-jp fonts-theano fonts-theano-doc grcnum grcnum-doc
-  karnaugh karnaugh-doc lipsum make-html make-markdown matrix matrix-doc
-  musikui num-conversion siunitx uline zrbase)
- Overriding dist with user installed one
- Not gathering system fonts
- Installing libraries: (arrows base dist fonts-dejavu zrbase)
- Removing destination /tmp/Satyrographos88f2bewith_env/dist
- Installation completed!
- 
- Compatibility notice for library zrbase:
- 
-   Packages have been renamed.
-   
-     zexn0.satyg -> zrbase/zexn0.satyg
-     zfmt0.satyg -> zrbase/zfmt0.satyg
-     zl0.satyg -> zrbase/zl0.satyg
-     zlist0.satyg -> zrbase/zlist0.satyg
-     zlog0.satyg -> zrbase/zlog0.satyg
-     zmtdoc0.satyh -> zrbase/zmtdoc0.satyh
-     znum0.satyg -> zrbase/znum0.satyg
-     zp0.satyg -> zrbase/zp0.satyg
-     zrandom0.satyg -> zrbase/zrandom0.satyg
-     zrbase0.satyg -> zrbase/zrbase0.satyg
-     zresult0.satyg -> zrbase/zresult0.satyg
-     zs0.satyg -> zrbase/zs0.satyg
- 
- Setting up SATySFi env at /tmp/Satyrographos88f2bewith_env 
- satysfi out>  ---- ---- ---- ----
- satysfi out>   target file: 'examples.pdf'
- satysfi out>   dump file: 'examples.satysfi-aux' (will be created)
- satysfi out>   parsing 'examples.saty' ...
- satysfi out> ! [Syntax Error at Parser] at "examples.saty", line 51, characters 15-17:
- Uncaught exception:
-   
-   (Failure
-    "Command exited with code 1: satysfi -C /tmp/Satyrographos88f2bewith_env examples.saty -o examples.pdf -b --debug-show-bbox --debug-show-block-bbox")
- 
- Raised at file "process-lib/src/process.ml", line 412, characters 11-22
- Called from file "process-lib/src/process.ml", line 516, characters 14-54
- Called from file "src/command/opam.ml", line 46, characters 6-122
- Called from file "bin/commandOpam.ml", line 28, characters 1-111
- Called from file "src/command.ml", line 2451, characters 8-238
- Called from file "src/exn.ml", line 111, characters 6-10
```

2020-09-09 09:31 UTC, na4zagin3 commented on packages/satysfi-arrows-doc/satysfi-arrows-doc.0.1.0/opam
> +  "satysfi" {>= "0.0.5" & < "0.0.6"}
Do you want me to apply a patch to exclude https://github.com/uemurax/satysfi-arrows/blob/9b43d36bda2ce6df507baad780a9c0cfc94ab917/docs/examples.saty#L51 when SATySFi is 0.0.5 stable?

2020-09-09 15:45 UTC, uemurax commented on packages/satysfi-arrows-doc/satysfi-arrows-doc.0.1.0/opam
> +  "satysfi" {>= "0.0.5" & < "0.0.6"}
The package contains math commands with optional arguments. One will sometimes want to give only the second optional argument, but `?*` is only supported by the development version of SATySFi. So, I think the package should not support the stable version to avoid confusion.

Sorry for bothering you.

2020-09-10 09:29 UTC, na4zagin3 commented on packages/satysfi-arrows-doc/satysfi-arrows-doc.0.1.0/opam
> +  "satysfi" {>= "0.0.5" & < "0.0.6"}
You are not bothering me!  Then, let me suggest changing the version restriction.

2020-09-10 09:33 UTC, na4zagin3 requested changes
Could you please remove support for SATySFi 0.0.5 stable?  Thanks!

2020-09-10 09:33 UTC, na4zagin3 commented on packages/satysfi-arrows-doc/satysfi-arrows-doc.0.1.0/opam
> +  "satysfi" {>= "0.0.5" & < "0.0.6"}
```suggestion
  "satysfi" {>= "0.0.5+dev2020.09.05" & < "0.0.6"}
```

2020-09-10 12:12 UTC, na4zagin3 approved these changes

2020-09-10 12:18 UTC, na4zagin3 commented
Thank you!!

I confirmed now the CI passes, but the status has not been updated by some reason.  Let me reopen to re-trigger the CI.  I'll merge this as soon as the CI passes.

2020-09-10 13:15 UTC, merged