2 packages from yabaitechtokyo/satysfi-class-yabaitech at 0.0.6
na4zagin3/satyrographos-repo pull request #216
Opened 2020-10-19 10:39 UTC by zeptometer

This pull-request concerns:
-`satysfi-class-yabaitech.0.0.6`: The yabaitech.tokyo SATySFi class file
-`satysfi-class-yabaitech-doc.0.0.6`: Document: The yabaitech.tokyo SATySFi class file

---
* Homepage: https://github.com/yabaitechtokyo/satysfi-class-yabaitech
* Source repo: git+https://github.com/yabaitechtokyo/satysfi-class-yabaitech.git
* Bug tracker: https://github.com/yabaitechtokyo/satysfi-class-yabaitech/issues

---
:camel: Pull-request generated by opam-publish v2.0.2

2020-10-19 11:49 UTC, na4zagin3 commented on snapshot-stable-0-0-5.opam
> +  "satysfi-dist" {= "0.0.3+dev2019.02.10"}
Something went wrong.  Can you tell me the commit ids which master and origin/master branches point to?

2020-10-31 05:14 UTC, zeptometer commented
Sorry, I found my comment was not submitted 😢

2020-10-31 11:05 UTC, na4zagin3 commented on snapshot-stable-0-0-5.opam
> +  "satysfi-dist" {= "0.0.3+dev2019.02.10"}
Ah, I see.  The script assumes `origin/master` points to this repository's master branch.

Do you mind to revert daf57d5, change the remotes so that `origin/master` points to https://github.com/na4zagin3/satyrographos-repo/tree/master, and rerun the script?

2020-10-31 11:06 UTC, na4zagin3 commented on snapshot-develop.opam
> +  "satysfi-dist" {= "0.0.3+dev2019.02.10"}
It's not expected. See https://github.com/na4zagin3/satyrographos-repo/pull/216#discussion_r515485385

2020-10-31 11:06 UTC, na4zagin3 commented
No worries!  Do you mind to fix the problem, following https://github.com/na4zagin3/satyrographos-repo/pull/216#discussion_r515485385?

2020-11-03 05:37 UTC, na4zagin3 commented on snapshot-develop.opam
> +
```suggestion
```

2020-11-03 05:37 UTC, na4zagin3 commented on snapshot-stable-0-0-5.opam
> +
```suggestion
```

2020-11-03 07:53 UTC, na4zagin3 commented on snapshot-develop.opam
> +
```suggestion
  "satysfi-class-yabaitech-doc" {= "0.0.6"}

  "satysfi-class-yabaitech" {= "0.0.6"}

```

2020-11-03 07:53 UTC, na4zagin3 commented on snapshot-develop.opam
> +
```suggestion
  "satysfi-ruby-doc" {= "0.1.2"}

```

2020-11-03 07:53 UTC, na4zagin3 commented on snapshot-stable-0-0-5.opam
> +
```suggestion
  "satysfi-class-yabaitech-doc" {= "0.0.6"}

  "satysfi-class-yabaitech" {= "0.0.6"}

```

2020-11-03 07:53 UTC, na4zagin3 commented on snapshot-stable-0-0-5.opam
```suggestion
  "satysfi-ruby-doc" {= "0.1.2"}

  "satysfi-ruby" {= "0.1.2"}

```

2020-11-03 11:27 UTC, na4zagin3 commented
I'm sorry for my late response. Thanks for sending the package!

2020-11-04 08:52 UTC, zeptometer commented
Sorry for the late reply, I've resolved https://github.com/na4zagin3/satyrographos-repo/pull/216#discussion_r515485385 in my local repo. Seems you've already resolved the issue in this PR, thank you for that! Is there anything I should do before this PR gets merged?

2020-11-04 10:18 UTC, zeptometer commented
Oops, I've found that Satyristes should be fixed, (version should be `0.0.6` instead of `0.0.4`). I'll do a quick fix.

2020-11-04 12:18 UTC, na4zagin3 commented
Oops,I just forgot to merge this ticket..   Anyway, I’d be happy if you could run `satyrographos lint` on the project (you will want to opt in to the feature with setting an environment variable.)

2020-11-07 10:09 UTC, na4zagin3 commented
@zeptometer can you please let me know when it's ready? Thanks

2020-11-07 23:19 UTC, zeptometer commented
The issue with `opam-publish` is resolved and I've updated the PR.

2020-11-07 23:22 UTC, zeptometer commented
@na4zagin3 `satyrographos lint` gave the following error.
```
$ SATYROGRAPHOS_EXPERIMENTAL=1 satyrographos lint
Compatibility warning: You have opted in to use experimental features.
/home/zeptometer/code/yabaitech/satysfi-class-yabaitech/Satyristes:2:1: (module class-yabaitech):
Error:
  Something went wrong during working on dependency graphs.
(Failure
 "BUG: decode_path: File \"/tmp/Satyrographos2032f2lint/packages/class-yabaitech/table-of-contents/../chapter/commands.satyh\" is not found.")
Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
Called from Satyrographos_command__Lint.lint_module_dependency.verification.(fun).check_dependency.(fun) in file "src/command/lint.ml", line 282, characters 29-49
Called from Base__List.count_map in file "src/list.ml", line 408, characters 13-17
Called from Base__List.concat_map.aux in file "src/list.ml", line 636, characters 34-40
Called from Base__Result.try_with in file "src/result.ml", line 195, characters 9-15


1 problem(s) found.
```

The path `/tmp/Satyrographos2032f2lint/packages/class-yabaitech/table-of-contents/../chapter/commands.satyh` looks valid to me. Do I need to care this problem?

2020-11-08 05:57 UTC, na4zagin3 commented
@zeptometer Oops.  It was a bug in Satyrographos 0.0.2.7.  The latest develop version reports these errors.

tl;dr: They are caused by `class-yabaitech/page/page-number.satyg` requiring `base/block.satyh` and `class-yabaitech/theorem/repository.satyg` requiring `base/cross-ref.satyh`.

Anyway, I'm now working on reducing the redundant problems..

```
Compatibility warning: You have opted in to use experimental features.
/mnt/workspace/satysfi/packages/satysfi-class-yabaitech/src/typeset/review-comment.satyh:1.1-1.10:
Error: lib/dep/missing
  Missing dependency for “@require: base/block” (mode (Generic))

/mnt/workspace/satysfi/packages/satysfi-class-yabaitech/src/title/page.satyh:1.1-1.10:
Error: lib/dep/missing
  Missing dependency for “@require: base/block” (mode (Generic))

/mnt/workspace/satysfi/packages/satysfi-class-yabaitech/src/table-of-contents/page.satyh:1.1-1.10:
Error: lib/dep/missing
  Missing dependency for “@require: base/block” (mode (Generic))

/tmp/Satyrographos16bdc8lint/packages/class-yabaitech/table-of-contents/../chapter/commands.satyh:2.2-2.11:
Error: lib/dep/missing
  Missing dependency for “@require: base/block” (mode (Generic))

/tmp/Satyrographos16bdc8lint/packages/class-yabaitech/table-of-contents/../chapter/../bibliography/section.satyh:1.1-1.10:
Error: lib/dep/missing
  Missing dependency for “@require: base/block” (mode (Generic))

/mnt/workspace/satysfi/packages/satysfi-class-yabaitech/src/paragraph/commands.satyh:1.1-1.10:
Error: lib/dep/missing
  Missing dependency for “@require: base/block” (mode (Generic))

/mnt/workspace/satysfi/packages/satysfi-class-yabaitech/src/page/page-number.satyg:5.2-5.11:
Error: lib/dep/missing
  Missing dependency for “@require: base/block” (mode (Generic))

/mnt/workspace/satysfi/packages/satysfi-class-yabaitech/src/page/footer.satyh:2.2-2.11:
Error: lib/dep/missing
  Missing dependency for “@require: base/block” (mode (Generic))

/mnt/workspace/satysfi/packages/satysfi-class-yabaitech/src/figure/commands.satyh:2.2-2.11:
Error: lib/dep/missing
  Missing dependency for “@require: base/block” (mode (Generic))

/mnt/workspace/satysfi/packages/satysfi-class-yabaitech/src/document.satyh:2.2-2.11:
Error: lib/dep/missing
  Missing dependency for “@require: base/block” (mode (Generic))

/mnt/workspace/satysfi/packages/satysfi-class-yabaitech/src/colophon/page.satyh:3.2-3.11:
Error: lib/dep/missing
  Missing dependency for “@require: base/block” (mode (Generic))

/mnt/workspace/satysfi/packages/satysfi-class-yabaitech/src/chapter/commands.satyh:2.2-2.11:
Error: lib/dep/missing
  Missing dependency for “@require: base/block” (mode (Generic))

/tmp/Satyrographos16bdc8lint/packages/class-yabaitech/chapter/../bibliography/section.satyh:1.1-1.10:
Error: lib/dep/missing
  Missing dependency for “@require: base/block” (mode (Generic))

/mnt/workspace/satysfi/packages/satysfi-class-yabaitech/src/bibliography/section.satyh:1.1-1.10:
Error: lib/dep/missing
  Missing dependency for “@require: base/block” (mode (Generic))

/mnt/workspace/satysfi/packages/satysfi-class-yabaitech/src/theorem/repository.satyg:1.1-1.10:
Error: lib/dep/missing
  Missing dependency for “@require: base/cross-ref” (mode (Generic))

/mnt/workspace/satysfi/packages/satysfi-class-yabaitech/src/table-of-contents/repository.satyg:1.1-1.10:
Error: lib/dep/missing
  Missing dependency for “@require: base/cross-ref” (mode (Generic))

/tmp/Satyrographos16bdc8lint/packages/class-yabaitech/table-of-contents/../chapter/repository.satyg:1.1-1.10:
Error: lib/dep/missing
  Missing dependency for “@require: base/cross-ref” (mode (Generic))

/tmp/Satyrographos16bdc8lint/packages/class-yabaitech/table-of-contents/../chapter/../table-of-contents/repository.satyg:1.1-1.10:
Error: lib/dep/missing
  Missing dependency for “@require: base/cross-ref” (mode (Generic))

/mnt/workspace/satysfi/packages/satysfi-class-yabaitech/src/figure/repository.satyg:1.1-1.10:
Error: lib/dep/missing
  Missing dependency for “@require: base/cross-ref” (mode (Generic))

/mnt/workspace/satysfi/packages/satysfi-class-yabaitech/src/chapter/repository.satyg:1.1-1.10:
Error: lib/dep/missing
  Missing dependency for “@require: base/cross-ref” (mode (Generic))

/tmp/Satyrographos16bdc8lint/packages/class-yabaitech/chapter/../table-of-contents/repository.satyg:1.1-1.10:
Error: lib/dep/missing
  Missing dependency for “@require: base/cross-ref” (mode (Generic))

/mnt/workspace/satysfi/packages/satysfi-class-yabaitech/src/page/page-number.satyg:3.2-3.11:
Error: lib/dep/missing
  Missing dependency for “@require: base/pager” (mode (Generic))

/mnt/workspace/satysfi/packages/satysfi-class-yabaitech/src/document.satyh:5.2-5.11:
Error: lib/dep/missing
  Missing dependency for “@require: base/pager” (mode (Generic))

23 problem(s) found.
```

2020-11-08 10:47 UTC, zeptometer commented
Thank you!

2020-11-13 10:11 UTC, zeptometer commented
Oh sorry, I misunderstood that this PR is merged...

2020-11-13 10:19 UTC, zeptometer commented
> tl;dr: They are caused by class-yabaitech/page/page-number.satyg requiring base/block.satyh and class-yabaitech/theorem/repository.satyg requiring base/cross-ref.satyh.

Could you elaborate on what is the problem I am supposed to fix? At least I cannot remove "@require base/block.satyh" from page-number.satyg.

2020-11-13 15:10 UTC, na4zagin3 commented
Shouldn't those `*.satyg` (e.g., page-number.satyg) packages be renamed with `*.satyh` (page-number.satyh) because they depend on packages that are unavailable in the text mode?

This is the latest lint result.

```
/home/mrty/Documents/Development/satysfi/packages/satysfi-class-yabaitech/src/page/page-number.satyg:5.2-5.11:
Error: lib/dep/missing
  Missing dependency for “@require: base/block” (mode (Generic))

/home/mrty/Documents/Development/satysfi/packages/satysfi-class-yabaitech/src/theorem/repository.satyg:1.1-1.10:
Error: lib/dep/missing
  Missing dependency for “@require: base/cross-ref” (mode (Generic))

/home/mrty/Documents/Development/satysfi/packages/satysfi-class-yabaitech/src/table-of-contents/repository.satyg:1.1-1.10:
Error: lib/dep/missing
  Missing dependency for “@require: base/cross-ref” (mode (Generic))

/home/mrty/Documents/Development/satysfi/packages/satysfi-class-yabaitech/src/chapter/repository.satyg:1.1-1.10:
Error: lib/dep/missing
  Missing dependency for “@require: base/cross-ref” (mode (Generic))

/home/mrty/Documents/Development/satysfi/packages/satysfi-class-yabaitech/src/table-of-contents/repository.satyg:1.1-1.10:
Error: lib/dep/missing
  Missing dependency for “@require: base/cross-ref” (mode (Generic))

/home/mrty/Documents/Development/satysfi/packages/satysfi-class-yabaitech/src/figure/repository.satyg:1.1-1.10:
Error: lib/dep/missing
  Missing dependency for “@require: base/cross-ref” (mode (Generic))

/home/mrty/Documents/Development/satysfi/packages/satysfi-class-yabaitech/src/chapter/repository.satyg:1.1-1.10:
Error: lib/dep/missing
  Missing dependency for “@require: base/cross-ref” (mode (Generic))

/home/mrty/Documents/Development/satysfi/packages/satysfi-class-yabaitech/src/table-of-contents/repository.satyg:1.1-1.10:
Error: lib/dep/missing
  Missing dependency for “@require: base/cross-ref” (mode (Generic))

/home/mrty/Documents/Development/satysfi/packages/satysfi-class-yabaitech/src/page/page-number.satyg:3.2-3.11:
Error: lib/dep/missing
  Missing dependency for “@require: base/pager” (mode (Generic))

9 problem(s) found.
```

2020-11-15 01:56 UTC, zeptometer commented
Ah, I see. Thank you for the explanation. I agree with your point and I've fixed the issue.

2020-11-15 05:30 UTC, na4zagin3 requested changes
MD5 hash should be updated too.

2020-11-15 05:30 UTC, na4zagin3 commented on packages/satysfi-class-yabaitech-doc/satysfi-class-yabaitech-doc.0.0.6/opam
> +    "md5=f6fb81a1a8d8d72fffe856b85cf08a4a"
```suggestion
    "md5=ffc96b861bd719a133f3e714fd57ece7"
```

2020-11-15 05:30 UTC, na4zagin3 commented on packages/satysfi-class-yabaitech/satysfi-class-yabaitech.0.0.6/opam
> +    "md5=f6fb81a1a8d8d72fffe856b85cf08a4a"
```suggestion
    "md5=ffc96b861bd719a133f3e714fd57ece7"
```

2020-11-15 05:31 UTC, na4zagin3 approved these changes

2020-11-15 08:27 UTC, zeptometer commented
oops, thank you for the update!

2020-11-15 11:32 UTC, na4zagin3 commented
Thank you!!

2020-11-15 11:32 UTC, merged