2 packages from puripuri2100/SATySFi-textmode-latex-packages at 0.2.0
na4zagin3/satyrographos-repo pull request #225
Opened 2020-11-16 14:26 UTC by puripuri2100

This pull-request concerns:
-`satysfi-make-latex.0.2.0`: Outputting LaTeX file using SATySFi's text-mode
-`satysfi-make-latex-doc.0.2.0`: Document of make-latex Package

---
* Homepage: https://github.com/puripuri2100/SATySFi-make-latex
* Source repo: git+https://github.com/puripuri2100/SATySFi-make-latex.git
* Bug tracker: https://github.com/puripuri2100/SATySFi-make-latex/issues

---
:camel: Pull-request generated by opam-publish v2.0.2

2020-11-16 23:13 UTC, na4zagin3 requested changes
Thanks!  Can you address my comments?

2020-11-16 23:13 UTC, na4zagin3 commented on packages/satysfi-make-latex-doc/satysfi-make-latex-doc.0.2.0/opam
> +   "-name" "make-latex-doc"
Can you use double-hyphened options in this file since this requires Satyrographos 0.0.2.6 or later?  Single-hyphened options will be unsupported since Satyrographos 0.0.3.

2020-11-16 23:13 UTC, na4zagin3 commented on packages/satysfi-make-latex/satysfi-make-latex.0.2.0/opam
> +  "satysfi" {>= "0.0.3" & < "0.0.6"}
Is this dependency correct?  IIRC SATySfi 0.0.3 does not support the text mode.  Additionally, do you really want to support SATySFi 0.0.4?

2020-11-17 05:06 UTC, puripuri2100 commented
I have fixed.
Is this okay?

2020-11-17 07:19 UTC, na4zagin3 approved these changes

2020-11-17 07:20 UTC, na4zagin3 commented
LGTM.  Thanks!

2020-11-17 07:20 UTC, merged