Packages satysfi-fonts-charis-sil.1.0.0 and satysfi-fonts-charis-sil-doc.1.0.0
na4zagin3/satyrographos-repo pull request #255
Opened 2021-01-19 10:16 UTC by yuhr

This pull-request concerns:
-`satysfi-fonts-charis-sil.1.0.0`: SATySFi Font Package for Charis SIL
-`satysfi-fonts-charis-sil-doc.1.0.0`: Document of SATySFi Font Package for Charis SIL

---
* Homepage: https://github.com/yuhr/satysfi-fonts-charis-sil
* Source repo: git+https://github.com/yuhr/satysfi-fonts-charis-sil.git
* Bug tracker: https://github.com/yuhr/satysfi-fonts-charis-sil/issues

---
:camel: Pull-request generated by opam-publish v2.0.3

2021-01-20 09:13 UTC, na4zagin3 commented
Let me try again.

2021-01-20 15:57 UTC, na4zagin3 requested changes

2021-01-20 15:57 UTC, na4zagin3 commented on packages/satysfi-fonts-charis-sil/satysfi-fonts-charis-sil.1.0.0/opam
> +license: "MIT"
Can you update the license?

```suggestion
license: "OFL-1.0"
```

2021-01-20 15:57 UTC, na4zagin3 commented on packages/satysfi-fonts-charis-sil-doc/satysfi-fonts-charis-sil-doc.1.0.0/opam
> +]
```suggestion
]
url {
  src:
    "https://github.com/yuhr/satysfi-fonts-charis-sil/archive/v1.0.0.tar.gz"
  checksum: [
    "md5=738e8783abe0522fc4f67dbd1b7045dc"
    "sha512=bc56c9a07d86d9586da1026434866665e8c9957d4619937011123b362fdce643665ca21bed3cc6fbed14a131023977b140de12af5beb2bbf53d29a15ff37329d"
  ]
}
```

2021-01-20 15:57 UTC, na4zagin3 commented on packages/satysfi-fonts-charis-sil/satysfi-fonts-charis-sil.1.0.0/opam
> +]
```suggestion
]
url {
  src:
    "https://github.com/yuhr/satysfi-fonts-charis-sil/archive/v1.0.0.tar.gz"
  checksum: [
    "md5=738e8783abe0522fc4f67dbd1b7045dc"
    "sha512=bc56c9a07d86d9586da1026434866665e8c9957d4619937011123b362fdce643665ca21bed3cc6fbed14a131023977b140de12af5beb2bbf53d29a15ff37329d"
  ]
}
```

2021-01-20 15:58 UTC, na4zagin3 approved these changes

2021-01-20 16:32 UTC, na4zagin3 commented
@yuhr now it's ready to choose the follow-up actions.

2021-01-22 14:32 UTC, na4zagin3 commented
I'm merging this package.  Thanks!

2021-01-22 14:33 UTC, merged

2021-01-23 17:10 UTC, yuhr commented
@na4zagin3 Thanks, and sorry for being late 😭 By the way, I definitely recommend using more clear words for the automation instructions, for example "wait until CI passes", and "tick checkboxes" instead of "choose".

2021-01-24 13:36 UTC, na4zagin3 commented
It makes sense.  I'll address them.  Thanks!