2 packages from puripuri2100/SATySFi-fonts-inconsolata at 3.001
na4zagin3/satyrographos-repo pull request #265
Opened 2021-01-24 13:31 UTC by puripuri2100

This pull-request concerns:
-`satysfi-fonts-inconsolata.3.001`: SATySFi Font Package for inconsolata fonts
-`satysfi-fonts-inconsolata-doc.3.001`: Document of SATySFi Font Package for inconsolata fonts

---
* Homepage: https://github.com/puripuri2100/SATySFi-fonts-inconsolata
* Source repo: git+https://github.com/puripuri2100/SATySFi-fonts-inconsolata.git
* Bug tracker: https://github.com/puripuri2100/SATySFi-fonts-inconsolata/issues

---
:camel: Pull-request generated by opam-publish v2.0.2

2021-01-24 13:42 UTC, na4zagin3 requested changes
Thanks!  Can you fix the following lines?

2021-01-24 13:42 UTC, na4zagin3 commented on packages/satysfi-fonts-inconsolata-doc/satysfi-fonts-inconsolata-doc.3.001/opam
> +  "satyrographos" {>= "0.0.2" & < "0.0.3"}
GNU-style long options requires Satyrographos 0.0.2.6 or later.

```suggestion
  "satyrographos" {>= "0.0.2.6" & < "0.0.3"}
```

2021-01-24 13:42 UTC, na4zagin3 commented on packages/satysfi-fonts-inconsolata/satysfi-fonts-inconsolata.3.001/opam
> +  "satyrographos" {>= "0.0.2" & < "0.0.3"}
GNU-style long options requires Satyrographos 0.0.2.6 or later.

```suggestion
  "satyrographos" {>= "0.0.2.6" & < "0.0.3"}
```

2021-01-24 13:42 UTC, na4zagin3 commented on packages/satysfi-fonts-inconsolata-doc/satysfi-fonts-inconsolata-doc.3.001/opam
> +  "satysfi-fonts-inconsolata" { = "%{version}%" }
You need to add a dependency on `satysfi-dist`.

```suggestion
  "satysfi-dist"
  "satysfi-fonts-inconsolata" { = "%{version}%" }
```

2021-01-24 13:46 UTC, puripuri2100 commented
thank you! 👍

2021-01-27 12:13 UTC, na4zagin3 commented
Hmm, the current CI does not handle a case where a package supports SATySFi 0.0.4 but does not support Satyrographos 0.0.2.5.

Let me fix the CI.  If you want to merge this PR ASAP, you can drop support of SATySFi 0.0.4.

2021-01-27 12:19 UTC, puripuri2100 reviewed
I choose drop support of SATySFi 0.0.4.

2021-01-27 12:19 UTC, puripuri2100 commented on packages/satysfi-fonts-inconsolata-doc/satysfi-fonts-inconsolata-doc.3.001/opam
> +  "satysfi" {>= "0.0.4" & < "0.0.6"}
```suggestion
  "satysfi" {>= "0.0.5" & < "0.0.6"}
```

2021-01-27 12:19 UTC, puripuri2100 commented on packages/satysfi-fonts-inconsolata/satysfi-fonts-inconsolata.3.001/opam
> +  "satysfi" {>= "0.0.4" & < "0.0.6"}
```suggestion
  "satysfi" {>= "0.0.5" & < "0.0.6"}
```

2021-01-27 15:04 UTC, na4zagin3 commented
Thank you!

2021-01-27 15:04 UTC, na4zagin3 approved these changes

2021-01-27 15:04 UTC, merged