2 packages from monaqa/satysfi-railway at 0.1.0
na4zagin3/satyrographos-repo pull request #352
Opened 2021-06-06 12:02 UTC by monaqa

This pull-request concerns:
- `satysfi-railway.0.1.0`: Drawing library for SATySFi
- `satysfi-railway-doc.0.1.0`: Drawing library for SATySFi

---
* Homepage: https://github.com/monaqa/satysfi-railway
* Source repo: git+https://github.com/monaqa/satysfi-railway.git
* Bug tracker: https://github.com/monaqa/satysfi-railway/issues

2021-06-06 13:33 UTC, na4zagin3 requested changes

2021-06-06 13:33 UTC, na4zagin3 commented on packages/satysfi-railway-doc/satysfi-railway-doc.0.1.0/opam
> +  "satysfi-dist"
Declaration duplicated

```suggestion
```

2021-06-06 13:33 UTC, na4zagin3 commented on packages/satysfi-railway-doc/satysfi-railway-doc.0.1.0/opam
> +  "satysfi-base"
Can you specify the version range?

```suggestion
  "satysfi-base" { >= "1.4.0" & < "2.0.0" }
```

2021-06-06 13:33 UTC, na4zagin3 commented on packages/satysfi-railway/satysfi-railway.0.1.0/opam
> +  "satysfi-base"
Can you specify the version range?

```suggestion
  "satysfi-base" { >= "1.4.0" & < "2.0.0" }
```

2021-06-06 13:33 UTC, na4zagin3 commented on packages/satysfi-railway-doc/satysfi-railway-doc.0.1.0/opam
> +license: "MIT" # Choose what you want
I'd remove the comment since, technically speaking, it can be interpreted that you allow users to choose the license of the project.

```suggestion
license: "MIT"
```

2021-06-07 23:12 UTC, monaqa commented
Thank you so much. Could you please apply the changes?

2021-06-08 07:55 UTC, na4zagin3 approved these changes

2021-06-08 10:56 UTC, merged

2021-06-08 11:04 UTC, na4zagin3 commented
Thank you!