Add satysfi-latexcmds v0.1.0
na4zagin3/satyrographos-repo pull request #360
Opened 2021-07-01 06:24 UTC by yasuo-ozu

2021-07-01 15:27 UTC, yasuo-ozu commented
I will add satysfi-latexcmds-doc later, so please wait.

2021-07-01 15:37 UTC, na4zagin3 requested changes

2021-07-01 15:37 UTC, na4zagin3 commented on packages/satysfi-latexcmds/satysfi-latexcmds.0.1.0/opam
> +license: "LGPL"
Can you set a SPDX License Identifier?  This should be `LGPL-3.0-or-later` or `LGPL-3.0-only`.

2021-07-01 15:37 UTC, na4zagin3 commented on packages/satysfi-latexcmds/satysfi-latexcmds.0.1.0/opam
> +  "satyrographos" {>= "0.0.2" & < "0.0.3"}
Options with double hyphens have been supported since 0.0.2.6

```suggestion
  "satyrographos" {>= "0.0.2.6" & < "0.0.3"}
```

2021-07-02 08:07 UTC, yasuo-ozu commented on packages/satysfi-latexcmds/satysfi-latexcmds.0.1.0/opam
> +license: "LGPL"
Thanks for review. I added `LGPL-3.0-or-later`.

2021-07-02 08:09 UTC, yasuo-ozu commented
Thank you for discussion. I finished adding `satysfi-latexcmds-doc`, but does the CI start again?

2021-07-02 08:11 UTC, yasuo-ozu commented
https://github.com/na4zagin3/satyrographos-repo/actions/runs/992885970

2021-07-02 09:29 UTC, na4zagin3 requested changes
Can you address the following problems?

1.  `packages/satysfi-latexcmds-doc/satysfi-latexcmds.0.1.0/opam` should be renamed for packages/satysfi-latexcmds-doc/satysfi-latexcmds-doc.0.1.0/opam` 
2. doc module `satysfi-latexcmds-doc` in `Satyristes` lacks dependency on `satysfi-latexcmds`

2021-07-02 09:31 UTC, na4zagin3 commented
Since this is your first contribution to this repository, GitHub requires me to run the CI...

2021-07-03 05:46 UTC, yasuo-ozu commented
Thanks for reviewing. I fixed these problems.

2021-07-04 06:00 UTC, na4zagin3 approved these changes

2021-07-04 06:00 UTC, na4zagin3 commented
Thank you!

2021-07-04 06:00 UTC, merged