2 packages from monaqa/slydifi at 0.4.0
na4zagin3/satyrographos-repo pull request #363
Opened 2021-07-09 14:38 UTC by monaqa

This pull-request concerns:
- `satysfi-class-slydifi.0.4.0`: A SATySFi document class for creating presentations slides
- `satysfi-class-slydifi-doc.0.4.0`: A SATySFi document class for creating presentations slides

---
* Homepage: https://github.com/monaqa/slydifi
* Source repo: git+https://github.com/monaqa/slydifi.git
* Bug tracker: https://github.com/monaqa/slydifi/issues
*

2021-07-15 16:37 UTC, na4zagin3 requested changes
Thank you for sending the new version of slydifi!

Can you please add upper bounds to the version constraints?

2021-07-15 16:37 UTC, na4zagin3 commented on packages/satysfi-class-slydifi/satysfi-class-slydifi.0.4.0/opam
> +  "satysfi-railway" {>= "0.1.0"}
Can you specify the upper bounds like these?

```suggestion
  "satysfi-figbox" {>= "0.1.3" & < "0.2.0"}}
  "satysfi-base" {>= "1.0.0" & < "2.0.0"}
  "satysfi-railway" {>= "0.1.0" & < "0.2.0"}
```

2021-07-15 16:37 UTC, na4zagin3 commented on packages/satysfi-class-slydifi-doc/satysfi-class-slydifi-doc.0.4.0/opam
> +  "satysfi-easytable" {>= "1.0.0"}
Can you specify the upper bound?

```suggestion
  "satysfi-easytable" {>= "1.0.0" & < "2.0.0"}
```

2021-07-16 03:17 UTC, monaqa commented
Thank you for your review. Fixed.

2021-07-16 12:55 UTC, na4zagin3 commented
Let me rerun the CI by reopening the ticket.

2021-07-16 22:27 UTC, na4zagin3 approved these changes

2021-07-16 22:28 UTC, na4zagin3 commented
Thank you!

2021-07-16 22:28 UTC, merged