2 packages from abenori/satysfi-pagestyle at 1.0.0
na4zagin3/satyrographos-repo pull request #366
Opened 2021-08-17 14:17 UTC by abenori

2021-08-18 12:27 UTC, na4zagin3 requested changes

2021-08-18 12:27 UTC, na4zagin3 commented on packages/satysfi-pagestyle-doc/satysfi-pagestyle-doc.1.0.0/opam
> +  "satysfi" { >= "0.0.5" }
Can you specify the upper bound?

```suggestion
  "satysfi" { >= "0.0.5" & < "0.0.7" }
```

2021-08-18 12:27 UTC, na4zagin3 commented on packages/satysfi-pagestyle-doc/satysfi-pagestyle-doc.1.0.0/opam
> +  "satysfi-pagestyle"
Can you specify the version constraint of the main library?

```suggestion
  "satysfi-pagestyle" {= "%{version}%"}
```

2021-08-18 12:27 UTC, na4zagin3 commented on packages/satysfi-pagestyle/satysfi-pagestyle.1.0.0/opam
> +Brilliant description comes here.
Do you mind to add a short description here or remove the `description` field?

2021-08-18 13:19 UTC, na4zagin3 commented on packages/satysfi-pagestyle/satysfi-pagestyle.1.0.0/opam
> +  "satysfi-pagenumber"
Can you specify version constraints?

```suggestion
  "satysfi-pagenumber" { >= "1.0.0" & < "2.0.0" }
```

2021-08-19 09:29 UTC, abenori commented
Thank you. I modified them,

2021-08-19 16:00 UTC, na4zagin3 approved these changes

2021-08-19 16:00 UTC, na4zagin3 commented
LGTM.  Let me reopen the PR to rerun the CI.

2021-08-20 16:12 UTC, na4zagin3 commented
Let me reopen the PR to rerun the CI.

2021-08-20 17:51 UTC, na4zagin3 commented
Thanks!

2021-08-20 17:51 UTC, merged