2 packages from abenori/satysfi-pagenumber at 1.0.0
na4zagin3/satyrographos-repo pull request #367
Opened 2021-08-17 14:17 UTC by abenori

2021-08-18 11:49 UTC, na4zagin3 commented
Let me reopen this PR to rerun the GitHub Actions.

2021-08-18 12:23 UTC, na4zagin3 requested changes

2021-08-18 12:23 UTC, na4zagin3 commented on packages/satysfi-pagenumber-doc/satysfi-pagenumber-doc.1.0.0/opam
> +  "satysfi" { >= "0.0.5" }
Can you specify the upper bound?

```suggestion
  "satysfi" { >= "0.0.5" & < "0.0.7"}
```

2021-08-18 12:23 UTC, na4zagin3 commented on packages/satysfi-pagenumber-doc/satysfi-pagenumber-doc.1.0.0/opam
> +  "satysfi-pagenumber"
Can you specify the version constraint of the main library?

```suggestion
  "satysfi-pagenumber" {= "%{version}%"}
```

2021-08-18 12:26 UTC, na4zagin3 commented on packages/satysfi-pagenumber/satysfi-pagenumber.1.0.0/opam
> +Brilliant description comes here.
Do you mind to add a short description here or remove the `description` field?

2021-08-19 09:27 UTC, abenori commented
Thank you. I modified.

2021-08-19 15:58 UTC, na4zagin3 approved these changes

2021-08-19 15:59 UTC, na4zagin3 commented
LGTM.  Thank you!

2021-08-19 15:59 UTC, merged