2 packages from puripuri2100/satysfi-code-printer at 1.0.0
na4zagin3/satyrographos-repo pull request #373
Opened 2021-09-12 04:08 UTC by puripuri2100

2021-09-13 16:04 UTC, na4zagin3 requested changes
Can you fix these?

2021-09-14 11:31 UTC, puripuri2100 commented
`read-file`という、v0.0.6には含まれていないプリミティブを使用しているのですが、どのようにSATySFi本体のバージョンを指定すればよいのでしょうか？

2021-09-14 16:22 UTC, na4zagin3 commented
@puripuri2100 Satyrographos Repo では https://github.com/gfngfn/SATySFi/pull/167 を先取りしているので、
```opam
  "satysfi" { >= "0.0.6-53-g2867e4d9" & < "0.0.7" }
```
のように開発版を指定して下さい（形式については https://git-scm.com/docs/git-describe#_examples をご覧下さい）。

2021-09-14 16:26 UTC, na4zagin3 requested changes

2021-09-14 16:26 UTC, na4zagin3 commented on packages/satysfi-code-printer-doc/satysfi-code-printer-doc.1.0.0/opam
> +  "satysfi" { >= "0.0.6" & < "0.0.7" }
```suggestion
  "satysfi" { >= "0.0.6-53-g2867e4d9" & < "0.0.7" }
```

2021-09-14 16:26 UTC, na4zagin3 commented on packages/satysfi-code-printer/satysfi-code-printer.1.0.0/opam
> +  "satysfi" { >= "0.0.6" & < "0.0.7" }
```suggestion
  "satysfi" { >= "0.0.6-53-g2867e4d9" & < "0.0.7" }
```

2021-09-14 21:34 UTC, puripuri2100 commented
ありがとうございます

2021-09-15 15:31 UTC, na4zagin3 approved these changes

2021-09-15 15:31 UTC, na4zagin3 commented
ありがとうございます！

2021-09-15 15:31 UTC, merged