Add SATySFi v0.0.9
na4zagin3/satyrographos-repo pull request #562
Opened 2023-06-29 11:57 UTC by puripuri2100

ref: https://github.com/gfngfn/SATySFi/releases/tag/v0.0.9

2023-06-30 11:32 UTC, puripuri2100 commented
SATySFi 0.0.9と共存できるようにsatyrographosの依存関係を修正して新しくリリースする方針で解決すると良さそうでしょうか

2023-06-30 11:39 UTC, na4zagin3 commented
MRありがとうございます!
そうですね……。そうしましょう。最近手が付けられていなくてすみません……

2023-09-27 02:52 UTC, puripuri2100 commented
satyrographos 0.0.2.13を対象にするように設定しなおしました

2023-09-27 16:45 UTC, na4zagin3 requested changes

2023-09-27 16:45 UTC, na4zagin3 commented on packages/satysfi-dist/satysfi-dist.0.0.9/opam
> +  archive: "http://www.gust.org.pl/projects/e-foundry/latin-modern/download/lm2.004otf.zip"
Let's use https instead (see <https://github.com/na4zagin3/satyrographos-repo/pull/582>)

```suggestion
  archive: "https://www.gust.org.pl/projects/e-foundry/latin-modern/download/lm2.004otf.zip"
```

2023-09-27 16:45 UTC, na4zagin3 commented on packages/satysfi-dist/satysfi-dist.0.0.9/opam
> +  archive: "http://www.gust.org.pl/projects/e-foundry/lm-math/download/latinmodern-math-1959.zip"
Let's use https instead (see <https://github.com/na4zagin3/satyrographos-repo/pull/582>)

```suggestion
  archive: "https://www.gust.org.pl/projects/e-foundry/lm-math/download/latinmodern-math-1959.zip"
```

2023-09-27 16:48 UTC, na4zagin3 approved these changes

2023-09-27 16:50 UTC, na4zagin3 commented
ありがとうございます!

あれ、CIが走らないので、PRを開け直してみます

2023-09-27 17:18 UTC, na4zagin3 commented
oftedのバグっぽいですね……

2023-09-28 12:47 UTC, puripuri2100 commented
そのようですね

```
@require: stdjabook

let-inline ctx \font f it =
  let ctx =
    ctx
    |> set-font HanIdeographic (f, 1.0, 0.0)
    |> set-font Kana (f, 1.0, 0.0)
    |> set-font Latin (f, 1.0, 0.0)
    |> set-font OtherScript (f, 1.0, 0.0)
  in
  read-inline ctx it
in


document (|
  title = {otfed bug};
  author = {};
  show-title = true;
  show-toc = false;
|) '<
  +p{\font(`fonts-noto-sans:NotoSans-Regular`){a}}
  +p{\font(`fonts-noto-sans-cjk-jp:NotoSansCJKjp-Regular`){a}}
  +p{\font(`fonts-noto-serif-cjk-jp:NotoSerifCJKjp-Regular`){a}}
>
```

でバグの再現を確認しました。

2023-09-28 14:53 UTC, na4zagin3 commented
再現ありがたとうございます!  Issue 立ててみました
https://github.com/gfngfn/SATySFi/issues/413

2023-10-01 20:12 UTC, puripuri2100 commented
satysfi 0.0.9が一応使えるようになったっぽいので反映させます…
https://github.com/na4zagin3/satyrographos-repo/commit/4f22173bd17d3edc2ea79321b1f5b8f3c23b9d6e

2023-10-01 20:17 UTC, puripuri2100 commented
と思ったけれどもこれは`satysfi.0.0.10`のリリースを待つべきで、このPRはcloseしますね

2023-10-01 20:17 UTC, closed without merging